const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('vortex', {
  getState: () => ipcRenderer.invoke('get-state'),
  listServers: () => ipcRenderer.invoke('list-servers'),
  getBedrockState: () => ipcRenderer.invoke('get-bedrock-state'),
  launchBedrock: () => ipcRenderer.invoke('launch-bedrock'),
  refreshServerStatus: (id, force = false) => ipcRenderer.invoke('refresh-server-status', id, force),
  addServer: (server) => ipcRenderer.invoke('add-server', server),
  selectServer: (id) => ipcRenderer.invoke('select-server', id),
  removeServer: (id) => ipcRenderer.invoke('remove-server', id),
  markReleaseNewsSeen: () => ipcRenderer.invoke('mark-release-news-seen'),
  getAccountAvatar: (id) => ipcRenderer.invoke('get-account-avatar', id),
  selectAccountAvatar: (id) => ipcRenderer.invoke('select-account-avatar', id),
  resetAccountAvatar: (id) => ipcRenderer.invoke('reset-account-avatar', id),
  getAiState: () => ipcRenderer.invoke('ai-get-state'),
  saveAiKey: (key, provider, textModel) => ipcRenderer.invoke('ai-save-key', key, provider, textModel),
  removeAiKey: () => ipcRenderer.invoke('ai-remove-key'),
  generateAiCape: (prompt) => ipcRenderer.invoke('ai-generate-cape', prompt),
  createAiModProject: (prompt) => ipcRenderer.invoke('ai-create-mod-project', prompt),
  openAiOutput: (kind) => ipcRenderer.invoke('ai-open-output', kind),
  openLaunchLog: () => ipcRenderer.invoke('open-launch-log'),
  openCrashLog: () => ipcRenderer.invoke('open-crash-log'),
  getWebsiteCapeCatalogue: () => ipcRenderer.invoke('get-website-cape-catalogue'),
  selectWebsiteCape: (capeId) => ipcRenderer.invoke('select-website-cape', capeId),
  getCommunityState: () => ipcRenderer.invoke('community-get-state'),
  openCommunityLogin: () => ipcRenderer.invoke('community-login'),
  listCommunityPresets: () => ipcRenderer.invoke('community-list-presets'),
  downloadCommunityPreset: (shareCode, filename) => ipcRenderer.invoke('community-download-preset', shareCode, filename),
  uploadCommunityPreset: (metadata) => ipcRenderer.invoke('community-upload-preset', metadata),
  listCommunitySkins: () => ipcRenderer.invoke('community-list-skins'),
  downloadCommunitySkin: (shareCode) => ipcRenderer.invoke('community-download-skin', shareCode),
  searchMods: (query, version, page) => ipcRenderer.invoke('search-mods', query, version, page),
  searchResourcePacks: (query, version, page) => ipcRenderer.invoke('search-resource-packs', query, version, page),
  downloadResourcePack: (version, pack) => ipcRenderer.invoke('download-resource-pack', version, pack),
  listResourcePacks: (version) => ipcRenderer.invoke('list-resource-packs', version),
  removeResourcePack: (version, fileName) => ipcRenderer.invoke('remove-resource-pack', version, fileName),
  downloadMod: (version, mod) => ipcRenderer.invoke('download-mod', version, mod),
  installModProject: (projectId, version) => ipcRenderer.invoke('install-mod-project', projectId, version),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  selectVersion: (version) => ipcRenderer.invoke('select-version', version),
  prepareInstance: (version) => ipcRenderer.invoke('prepare-instance', version),
  getInstanceSummary: (version) => ipcRenderer.invoke('get-instance-summary', version),
  openModsFolder: (version) => ipcRenderer.invoke('open-mods-folder', version),
  openInstanceFolder: (version) => ipcRenderer.invoke('open-instance-folder', version),
  openCosmeticsProfile: (version) => ipcRenderer.invoke('open-cosmetics-profile', version),
  listMods: (version) => ipcRenderer.invoke('list-mods', version),
  removeMod: (version, fileName) => ipcRenderer.invoke('remove-mod', version, fileName),
  toggleMod: (version, fileName) => ipcRenderer.invoke('toggle-mod', version, fileName),
  setCosmetics: (cosmetics) => ipcRenderer.invoke('set-cosmetics', cosmetics),
  showCosmeticsInfo: () => ipcRenderer.invoke('show-cosmetics-info'),
  login: () => ipcRenderer.invoke('login'),
  selectAccount: (id) => ipcRenderer.invoke('select-account', id),
  removeAccount: (id) => ipcRenderer.invoke('remove-account', id),
  logout: () => ipcRenderer.invoke('logout'),
  launch: (version, serverId = null) => ipcRenderer.invoke('launch', version, serverId),
  onStatus: (callback) => ipcRenderer.on('status', (_event, value) => callback(value)),
  onLog: (callback) => ipcRenderer.on('log', (_event, value) => callback(value)),
  onProgress: (callback) => ipcRenderer.on('progress', (_event, value) => callback(value)),
  onInstanceMaintenance: (callback) => ipcRenderer.on('instance-maintenance', (_event, value) => callback(value)),
  onCommunityState: (callback) => ipcRenderer.on('community-state', (_event, value) => callback(value)),
  onUpdateState: (callback) => ipcRenderer.on('update-state', (_event, value) => callback(value))
});
